{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lunazstudios",
    "module": "CourierAPI",
    "version": "1.21.11-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1.jar",
          "url": "CourierAPI-1.21.11-0.1.jar",
          "size": 30369,
          "sha512": "7dbd647a2f9fc10098c84a9631b6d3d81a49ea7520cc205e40f0723cffcadcb2e5eaee6dcdaf38ab84531d1952b96dcf3a9288921747c788e92b63c613341b65",
          "sha256": "b74c0f870994827ad05d400806a7cf5ca2f452f68d7b34b3396866df6c6fd717",
          "sha1": "b4093d45506a66de4f6e090b299bb4379dcf60f0",
          "md5": "f1515d31f01ef7362b03a368fd9f9379"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1.jar",
          "url": "CourierAPI-1.21.11-0.1.jar",
          "size": 30369,
          "sha512": "7dbd647a2f9fc10098c84a9631b6d3d81a49ea7520cc205e40f0723cffcadcb2e5eaee6dcdaf38ab84531d1952b96dcf3a9288921747c788e92b63c613341b65",
          "sha256": "b74c0f870994827ad05d400806a7cf5ca2f452f68d7b34b3396866df6c6fd717",
          "sha1": "b4093d45506a66de4f6e090b299bb4379dcf60f0",
          "md5": "f1515d31f01ef7362b03a368fd9f9379"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1-sources.jar",
          "url": "CourierAPI-1.21.11-0.1-sources.jar",
          "size": 18090,
          "sha512": "2c15e69c577e9cb26de9b1d77103dfd7035c6d5133523c55de8a0a44cf034ada245d7505c6fd67a1779b8ef32d6d1cbfd93ab29615d8f56c8bbd6d8922d9df87",
          "sha256": "8ff7d832e4b585978b81dc26c94c81ffb524119e48a2f83d8c9cf999ced15dc3",
          "sha1": "52eecd2c8e703e5e7d6442721a5ab7fe812e707f",
          "md5": "7dd19c1b896436b8934909a13ff5fe39"
        }
      ]
    }
  ]
}
