{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lunazstudios",
    "module": "CourierAPI",
    "version": "1.21.11-0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1.jar",
          "url": "CourierAPI-1.21.11-0.1.jar",
          "size": 30881,
          "sha512": "4edae13169a425d9a36be3d3b05500e070be5e38104be67fa83c0edd30ba9827cb3edc547cf023644e6351e45d25bea079f40712dda92321ca8c74b28eaa3b96",
          "sha256": "bc26b1c8d7bc38f7a625aff06ad2a0e79566c069cdf85e4c27de01991c959e15",
          "sha1": "39bb842ec823c485b60726d40defdbddae7dd656",
          "md5": "b22448046802f7fcea09111291281856"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.141.3+1.21.11"
          }
        }
      ],
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1.jar",
          "url": "CourierAPI-1.21.11-0.1.jar",
          "size": 30881,
          "sha512": "4edae13169a425d9a36be3d3b05500e070be5e38104be67fa83c0edd30ba9827cb3edc547cf023644e6351e45d25bea079f40712dda92321ca8c74b28eaa3b96",
          "sha256": "bc26b1c8d7bc38f7a625aff06ad2a0e79566c069cdf85e4c27de01991c959e15",
          "sha1": "39bb842ec823c485b60726d40defdbddae7dd656",
          "md5": "b22448046802f7fcea09111291281856"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CourierAPI-1.21.11-0.1-sources.jar",
          "url": "CourierAPI-1.21.11-0.1-sources.jar",
          "size": 18843,
          "sha512": "ecff3b3835052cc8338e844f39f2e6a2b4fdf8a43bf3a1a6f0efcde658c023916e0b02925b8f3a022247f292443cd95b7ba2dfc3f02d633ae6878ec10e218433",
          "sha256": "bb9d18e9005bbf19a679374dac60f1636490c3ed6b5f5adeba8561aee577d86a",
          "sha1": "76160665fa321c473fe5f2271a4e3f2a8ffb3ced",
          "md5": "34de7c0922522daf0a773788c8b03ec0"
        }
      ]
    }
  ]
}
